# 地址: https://github.com/Jarv1s0/Proxy_Script
# 版本: v2.2.1
# 更新: 2026 年 3 月 13 日

# ==================== 核心配置 ====================
# 基础配置
mode: rule
port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7895
ipv6: false
allow-lan: true
unified-delay: true
tcp-concurrent: true
log-level: warning
bind-address: '*'
find-process-mode: 'always'
keep-alive-interval: 15
keep-alive-idle: 600

# TUN模式配置
tun:
  enable: true
  stack: gvisor
  dns-hijack:
    - "any:53"
    - "tcp://any:53"
  auto-route: true
  auto-redirect: true
  auto-detect-interface: true
    
# DNS配置
dns:
  enable: true
  respect-rules: true
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  # 解析上游 DoH/DoT 的起始 DNS
  default-nameserver:
    - tls://223.5.5.5
    - tls://223.6.6.6
  # 代理路径用的国外上游（仅对需代理的非直连规则集域名）
  nameserver:
    - "https://1.1.1.1/dns-query"
    - "https://8.8.8.8/dns-query"
  # 直连路径专用上游（国内 DoH）
  direct-nameserver:
    - "https://dns.alidns.com/dns-query"
    - "https://doh.pub/dns-query"
  # 解析代理服务器的域名，防循环用国内
  proxy-server-nameserver:
    - "https://dns.alidns.com/dns-query"
    - "https://doh.pub/dns-query"
  # 配置查询访问域名使用的服务器
  nameserver-policy:
    # 直连类规则集匹配的域名绑定国内上游，首跳即国内，不触发国外→国内回切
    "rule-set:Direct,Private,China,fakeip-filter":
      - "https://dns.alidns.com/dns-query"
      - "https://doh.pub/dns-query"
  fake-ip-filter:
    - rule-set:Direct
    - rule-set:Private
    - rule-set:China
    - rule-set:fakeip-filter
  
# 实验性功能
experimental:
  quic-go-disable-gso: true  
  
# 配置存储
profile:
  store-selected: true
  store-fake-ip: true

# 流量嗅探
sniffer:
  enable: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  skip-domain:
    - "Mijia Cloud"
    - "+.push.apple.com"
    
 # ==================== 锚点配置 ====================   
# 锚点定义
UrlTest: &UrlTest {type: url-test, interval: 200, lazy: true, url: 'https://www.google.com/generate_204', hidden: true, include-all: true }
Select: &Select { type: select, hidden: false, include-all: true }
Global_settings: { exclude_regex: &global_exclude "AHK|排除1|排除2|5x|剩余流量|过期|回国|群|官网|客服|订阅|流量" }
# 地理位置匹配锚点
filters:
  - &FilterHK '(?i)港|🇭🇰|HK|Hong|HKG'
  - &FilterSG '(?i)坡|🇸🇬|SG|Sing|SIN|XSP'
  - &FilterJP '(?i)日|🇯🇵|JP|Japan|NRT|HND|KIX|CTS|FUK'
  - &FilterKR '(?i)韩|🇰🇷|韓|首尔|KR|KOR|Korea'
  - &FilterUS '(?i)美|🇺🇸|\bUS\b|USA|SJC|JFK|LAX|ORD|SFO'
  - &FilterTW '(?i)台|🇹🇼|TW|tai|TPE|TSA|KHH'
  - &FilterEU '(?i)德|法|英|意|荷|瑞|🇪🇺|FRA|CDG|LHR|AMS'

# ==================== 代理策略组 ====================
#代理组
proxy-groups:
  # --- 顶层业务分组 ---
  - { name: Proxy, type: select, proxies: [香港, 台湾, 日本, 新加坡, 美国, 韩国, 欧盟, ALL, DIRECT], icon: https://cdn.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/Rocket.png }
  - { name: YouTube, type: select, proxies: [美国, 香港, 台湾, 日本, 新加坡, 韩国, 欧盟], icon: https://cdn.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/YouTube.png }
  - { name: AI, type: select, proxies: [美国, 新加坡, 日本, 欧盟], icon: https://cdn.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/AI.png }
  - { name: Games, type: select, proxies: [香港, 台湾, 日本, 新加坡, 美国, DIRECT], icon: https://cdn.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/Steam.png }
  - { name: Google, type: select, proxies: [美国, 香港, 台湾, 日本, 新加坡, 韩国, 欧盟], icon: https://cdn.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/Google_Search.png } 
  - { name: GitHub, type: select, proxies: [香港, 台湾, 日本, 新加坡, 美国, 韩国, 欧盟], icon: https://cdn.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/GitHub.png }
  - { name: Telegram, type: select, proxies: [香港, 台湾, 日本, 新加坡, 美国, 韩国, 欧盟], icon: https://cdn.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/Telegram.png }

  # --- 底层地区筛选组 ---
  - { name: 香港, <<: *UrlTest, filter: *FilterHK, exclude-filter: *global_exclude, icon: https://cdn.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/Hong_Kong.png }
  - { name: 台湾, <<: *UrlTest, filter: *FilterTW, exclude-filter: *global_exclude, icon: https://cdn.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/Taiwan.png }
  - { name: 日本, <<: *UrlTest, filter: *FilterJP, exclude-filter: *global_exclude, icon: https://cdn.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/Japan.png }
  - { name: 新加坡, <<: *UrlTest, filter: *FilterSG, exclude-filter: *global_exclude, icon: https://cdn.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/Singapore.png }
  - { name: 韩国, <<: *UrlTest, filter: *FilterKR, exclude-filter: *global_exclude, icon: https://cdn.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/Korea.png }
  - { name: 美国, <<: *Select, filter: *FilterUS, exclude-filter: *global_exclude, icon: https://cdn.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/United_States.png }
  - { name: 欧盟, <<: *UrlTest, filter: *FilterEU, exclude-filter: *global_exclude, icon: https://cdn.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/European_Union.png } 
  - { name: ALL, type: select, include-all: true, exclude-filter: *global_exclude, icon: https://cdn.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/Global.png }

# ==================== 规则集 ====================
# 规则集行为模板
BehaviorDN: &BehaviorDN {type: http, behavior: domain, format: mrs, interval: 86400, proxy: Proxy}
BehaviorIP: &BehaviorIP {type: http, behavior: ipcidr, format: mrs, interval: 86400, proxy: Proxy}

# 规则提供者
rule-providers:  
  # 域名规则
  Tracking:       {<<: *BehaviorDN, url: https://github.com/666OS/rules/raw/release/mihomo/domain/Tracking.mrs}
  Advertising:    {<<: *BehaviorDN, url: https://github.com/666OS/rules/raw/release/mihomo/domain/Advertising.mrs} 
  Direct:         {<<: *BehaviorDN, url: https://github.com/666OS/rules/raw/release/mihomo/domain/Direct.mrs}
  Private:        {<<: *BehaviorDN, url: https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/private.mrs}
  Download:       {<<: *BehaviorDN, url: https://github.com/666OS/rules/raw/release/mihomo/domain/Download.mrs}
  fakeip-filter:  {<<: *BehaviorDN, url: https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/fakeip-filter.mrs}
  AI:             {<<: *BehaviorDN, url: https://github.com/666OS/rules/raw/release/mihomo/domain/AI.mrs} 
  GitHub:         {<<: *BehaviorDN, url: https://github.com/666OS/rules/raw/release/mihomo/domain/GitHub.mrs}    
  Telegram:       {<<: *BehaviorDN, url: https://github.com/666OS/rules/raw/release/mihomo/domain/Telegram.mrs}
  SteamCN:        {<<: *BehaviorDN, url: https://github.com/Jarv1s0/RuleList/raw/main/rules/SteamCN.mrs} 
  Games:          {<<: *BehaviorDN, url: https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/games.mrs}
  YouTube:        {<<: *BehaviorDN, url: https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/youtube.mrs}
  AppleCN:        {<<: *BehaviorDN, url: https://github.com/666OS/rules/raw/release/mihomo/domain/AppleCN.mrs}
  GoogleCN:       {<<: *BehaviorDN, url: https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/google-cn.mrs}
  Google:         {<<: *BehaviorDN, url: https://github.com/666OS/rules/raw/release/mihomo/domain/Google.mrs}
  Microsoft:      {<<: *BehaviorDN, url: https://github.com/666OS/rules/raw/release/mihomo/domain/Microsoft.mrs}
  GFW:            {<<: *BehaviorDN, url: https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/gfw.mrs}    
  Proxy:          {<<: *BehaviorDN, url: https://github.com/666OS/rules/raw/release/mihomo/domain/Proxy.mrs}
  China:          {<<: *BehaviorDN, url: https://github.com/666OS/rules/raw/release/mihomo/domain/China.mrs}
  # IP规则
  AdvertisingIP:  {<<: *BehaviorIP, url: https://github.com/666OS/rules/raw/release/mihomo/ip/Advertising.mrs}
  PrivateIP:      {<<: *BehaviorIP, url: https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/privateip.mrs}
  AIIP:           {<<: *BehaviorIP, url: https://github.com/666OS/rules/raw/release/mihomo/ip/AI.mrs}
  TelegramIP:     {<<: *BehaviorIP, url: https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/telegramip.mrs}   
  GoogleIP:       {<<: *BehaviorIP, url: https://github.com/666OS/rules/raw/release/mihomo/ip/Google.mrs}  
  ProxyIP:        {<<: *BehaviorIP, url: https://github.com/666OS/rules/raw/release/mihomo/ip/Proxy.mrs} 
  ChinaIP:        {<<: *BehaviorIP, url: https://github.com/666OS/rules/raw/release/mihomo/ip/China.mrs}
  
# ==================== 规则路由 ====================  
rules:
  # 1. 优先处理特定域名关键字 (DomainSet/Keyword)
  - DOMAIN-KEYWORD,1ytsub,DIRECT
  - DOMAIN-KEYWORD,jarv1s,Proxy
  - PROCESS-NAME,dota2.exe,DIRECT
  - PROCESS-NAME,language_server_windows_x64.exe,AI # Antigravity
  - PROCESS-NAME,Antigravity.exe,AI # Antigravity 
  # 拦截规则
  - RULE-SET,Tracking,REJECT
  - RULE-SET,Advertising,REJECT
  - OR,((AND,((DST-PORT,443),(NETWORK,UDP),(NOT,((GEOIP,CN))))),(DST-PORT,853)),REJECT # 拦截海外 QUIC 流量及全域 DoT 流量
  # 域名规则
  - RULE-SET,Private,DIRECT
  - RULE-SET,Direct,DIRECT
  - RULE-SET,SteamCN,DIRECT
  - RULE-SET,Download,DIRECT
  - RULE-SET,AppleCN,DIRECT
  - RULE-SET,AI,AI
  - RULE-SET,GitHub,GitHub
  - RULE-SET,Telegram,Telegram
  - RULE-SET,Games,Games
  - RULE-SET,YouTube,YouTube
  - RULE-SET,Microsoft,DIRECT
  - RULE-SET,Google,Google
  - RULE-SET,GoogleCN,Google
  - RULE-SET,GFW,Proxy
  - RULE-SET,Proxy,Proxy
  - RULE-SET,China,DIRECT
  # IP规则
  - RULE-SET,AdvertisingIP,REJECT,no-resolve
  - RULE-SET,PrivateIP,DIRECT,no-resolve
  - RULE-SET,AIIP,AI,no-resolve
  - RULE-SET,TelegramIP,Telegram,no-resolve
  - RULE-SET,GoogleIP,Google,no-resolve
  - RULE-SET,ProxyIP,Proxy,no-resolve
  - RULE-SET,ChinaIP,DIRECT
  - MATCH,Proxy
